name=Esp32NofrendobyDSN
version=0.9.0
author=derdacavga
maintainer=DSN Industries
sentence=Nofrendo NES Emulator Core for ESP32
paragraph=A port of Nofrendo specifically designed for ESP32-S3.
category=Games
url=https://github.com/derdacavga/Esp32-nes-emulator-by-DSN
architectures=esp32S3

includes=nofrendo.h
